# Generated by Django 4.0.3 on 2022-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True)),
                ('seats', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
