# Generated by Django 4.0.3 on 2022-03-02 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, null=True)),
                ('seats', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('Comedy', 'Comedy'), ('Sports', 'Sports'), ('Movie', 'Movie'), ('Music', 'Music')], default=1, max_length=20)),
                ('image', models.ImageField(default='default.jpeg', upload_to='event_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_person', models.IntegerField()),
                ('date_booked', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(max_length=15)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventbooking.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
