# Generated by Django 4.0.3 on 2022-03-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
