# Generated by Django 4.0.3 on 2022-03-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Credit Card', 'Credit Card')], max_length=15),
        ),
    ]
