# Generated by Django 4.0.3 on 2022-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooking', '0004_remove_ticket_amount_remove_ticket_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='event_pics'),
        ),
    ]
